### ISSUE TITLE
Negative matching

### ISSUE THREAD

**Issue by DavertMik** [chrisguitarguy/Counterpart#1]
_Ping: I wrote a message to you on reddit. Check inbox )_ 

As I discovered there should be an option to set in one matcher 2 assertion types: positive and negative. It's really needed because once you test that username is valid, you will check the username is invalid in a next test. So both assertions should live in the same class. 

It makes a matcher a bit more complicated as it should have 1 checking function, but in it should provide different messages and depending on a context.

As an idea:

``` php
<?php
namespace Assert;

class Equals extends ExpectedActual {

function __construct($target)
{
  $this->target = $target;
}

function matches($value)
{
  return $value == $this->target;
}

function assertFailMessage()
{
  return "was expected to equal ".str($this->target);
}

function refuteFailMessage()
{
  return "was not expected to equal ".str($this->target);
}

}
?>
```

**Comment by chrisguitarguy** [comment]
Hi, Thanks!

This is solved a bit differently as of now. There's a `LogicalNot` matcher that serves as a decorator around another matcher.

So you'd do something like this (for `IsEqual`):

``` php
use Counterpart\Matcher\LogicalNot;
use Counterpart\Matcher\IsEqual;

$notEqual = new LogicalNot(new IsEqual(1));
var_dump($notEqual->matches(2)); // true
var_dump($notEqual->matches(1)); // false
$message = (string)$notEqual; // $msg == "not is equal to 1"
```

Or using the `Counterpart\Matchers` API:

``` php
use Counterpart\Matchers;

$notEqual = Matchers::logicalNot(Matchers::isEqual(1));
var_dump($notEqual->matches(2)); // true
var_dump($notEqual->matches(1)); // false
$message = (string)$notEqual; // $msg == "not is equal to 1"
```

Unfortunately the assertion message sucks right now, but that's on the list of things to fix up.

**Comment by DavertMik** [comment]
Yep, the proper assertion messages is the place where I got stuck when I proptotyped my testing framework. Not always you can add just "not " to assertion message to create a handful description of negative assertion failure. 

```
logicalNot(isTrue)` => Failed asserting not true 
```

Does not sound right... Or

Let's assume situation, there is a custom matcher `ElementOnPage`. 
When assertion fails, there should be a message: `Element <h1> not found on page`.
In opposite case the message should contain found element itself: `Element < h1 >Welcome </h1> was unexpectedly found on page`

Thus, matcher should contain negative description in case it is used inside `LogicalNot`

**Comment by chrisguitarguy** [comment]
Right now every matcher's `__toString` method returns a phrase that starts with the word _is_.

The assertion messages come from the `Assert::assertThat` message and are of the format:

> Failed asserting that {THE VALUE} {MATCHER PHRASE}

Example:

> Failed asserting that array("one" => 2) is an array or ArrayAccess containing the key two

The logical not would be something like

> Failed asserting that array("two" => 2) is **not** an array or ArrayAccess containing the key two

I'd rather keep the matcher's string description generic and then have `LogicalNot` replace common words (is -> is not, was -> was not, has -> does not have, etc).

That, to me anyway, seems like a much cleaner way to do things and puts less of a burden on custom implementations of `Matcher`.

Admittedly `ElementOnPage` would be a bit awkward.

``` php
use Counterpart\Matcher;

class ElementOnPage implements Matcher
{
    public function matches($page)
    {
        // ...
    }

    public function __toString()
    {
        return "is a page containing {$this->elementName}";
    }
}
```

The negative assertion would come out something like:

> Failed asserting that {the page here} is not a page containing < h1 >

**Comment by chrisguitarguy** [comment]
Maybe `LogicalNot` is replacing the wrong stuff. Instead of the `is` may it should do stuff like:
- that contains -> that does not contain
- equals -> does not equal

Whatever it is, to keep the single `__toString` method (which I like), there needs to some sort of common vocabulary for matchers that's documented.

**Comment by DavertMik** [comment]
Yeah, I like `__toString` approach as well. 
But looks like there should a way to put custom texts in both assertion cases. Especially if you will print not only a message but diffs between actual and expected.

**Comment by chrisguitarguy** [comment]
Maybe some sort of [interface segregation](http://en.wikipedia.org/wiki/Interface_segregation_principle) is the answer here?

`LogicalNot` could handle common cases, as described above. That's going to get you pretty much most of the way there for a lot of use cases.

Then add a `MismatchDescribing` interface that can handle more complicated cases.

``` php
interface MismatchDescribing
{
    public function describeMismatch();
}
```

Whenever `LogicalNot` sees that interface it can call the `describeMismatch` function to print a better error message.

Thoughts?

**Comment by chrisguitarguy** [comment]
For custom texts in positive match cases, those can just go in the `__toString` method as normal.

Or maybe there should be a way for `Assert::assertThat` to see if a matcher can describe itself rather than using the default format (yet another interface probably).

**Comment by chrisguitarguy** [comment]
@DavertMik could you check out 01372a0b52b528eb81e0825beabfbe8467aa197d ??

I think it makes sense. Still keeps matchers easy to implement, but let's them (optionally) implement another interface that will give much nicer error messages.

**Comment by chrisguitarguy** [comment]
Closing, #2 is a decent solution for the 1.X versions of Counterpart, I think.
